apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ml-talk-deployment.yaml
- ml-talk-service.yaml
- ml-talk-ingress.yaml

images:
- name: harbor.riwi.dev/philiplehmann/ml-talk
  newName: harbor.riwi.dev/philiplehmann/ml-talk
  newTag: 22-12-13.18
