apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ml-talk-deployment.yaml
- ml-talk-service.yaml
- ml-talk-ingress.yaml

images:
- name: ghcr.io/philiplehmann/ml-talk
  newName: ghcr.io/philiplehmann/ml-talk
  newTag: 22-12-13.16