apiVersion: apps/v1
kind: Deployment
metadata:
  name: mltalk-philiplehmann
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mltalk-philiplehmann
  template:
    metadata:
      labels:
        app: mltalk-philiplehmann
    spec:
      imagePullSecrets:
        - name: docker-registry-github
      containers:
        - name: mltalk-philiplehmann
          image: ghcr.io/philiplehmann/ml-talk:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 3000
      restartPolicy: Always
