apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-talk-philiplehmann
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-talk-philiplehmann
  template:
    metadata:
      labels:
        app: ml-talk-philiplehmann
    spec:
      containers:
        - name: ml-talk-philiplehmann
          imagePullPolicy: IfNotPresent
          image: harbor.riwi.dev/philiplehmann/ml-talk:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
            capabilities: {}
      
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          startupProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
      restartPolicy: Always
