name: build & deploy

on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn lint
      - run: yarn typecheck

  build:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to github registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: true
          cache-from: type=registry,ref=ghcr.io/philiplehmann/ml-talk:buildcache
          cache-to: type=registry,ref=ghcr.io/philiplehmann/ml-talk:buildcache,mode=max
          tags: |
            ghcr.io/philiplehmann/ml-talk:latest
            ghcr.io/philiplehmann/ml-talk:$(date '+%y-%m-%d').${GITHUB_RUN_NUMBER}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: imranismail/setup-kustomize@v2
    - name: deploy
      run: |
        cd kustomize
        kustomize edit set image ml-talk-philiplehmann=ghcr.io/philiplehmann/ml-talk:$(date '+%y-%m-%d').${GITHUB_RUN_NUMBER}
        git add .
        git commit -m "Set `app` image tag to `$(date '+%y-%m-%d').${GITHUB_RUN_NUMBER}`"
        git push
        